In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np

In [3]:
#2. Print the NUMPY version and the configuration.
print("Numpy Version:", np.__version__)
print("Numpy Configuration:")
np.show_config()

Numpy Version: 1.21.5
Numpy Configuration:
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ANACONDA\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ANACONDA\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ANACONDA\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ANACONDA\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ANACONDA\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ANACONDA\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ANACONDA\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ANACONDA\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE4

In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

# a = np.random.rand(2, 3, 5)

# a = np.random.randn(2, 3, 5)

a = np.random.random((2, 3, 5))

#4. Print a.

print(a)

[[[0.26015744 0.67305176 0.93116771 0.2224573  0.25706671]
  [0.8331111  0.62592033 0.81572585 0.23120037 0.03364045]
  [0.91207502 0.27417193 0.79667205 0.15623792 0.76216763]]

 [[0.65941125 0.83452626 0.25647604 0.93335975 0.06279051]
  [0.67468439 0.07744533 0.32012986 0.57375164 0.13633176]
  [0.09294808 0.92302073 0.35460361 0.07305246 0.967641  ]]]


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5, 2, 3))


#6. Print b.
print(b)


#7. Do a and b have the same size? How do you prove that in Python code?

print(a.size == b.size)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
True


# 8. Are you able to add a and b? Why or why not?
# No, we are not able to add a and b because they are not the same shape

In [7]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b, (1, 2, 0)).reshape(2, 3, 5)

In [8]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
# Because they have the same shape
d = a + c

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)

[[[0.26015744 0.67305176 0.93116771 0.2224573  0.25706671]
  [0.8331111  0.62592033 0.81572585 0.23120037 0.03364045]
  [0.91207502 0.27417193 0.79667205 0.15623792 0.76216763]]

 [[0.65941125 0.83452626 0.25647604 0.93335975 0.06279051]
  [0.67468439 0.07744533 0.32012986 0.57375164 0.13633176]
  [0.09294808 0.92302073 0.35460361 0.07305246 0.967641  ]]]
[[[1.26015744 1.67305176 1.93116771 1.2224573  1.25706671]
  [1.8331111  1.62592033 1.81572585 1.23120037 1.03364045]
  [1.91207502 1.27417193 1.79667205 1.15623792 1.76216763]]

 [[1.65941125 1.83452626 1.25647604 1.93335975 1.06279051]
  [1.67468439 1.07744533 1.32012986 1.57375164 1.13633176]
  [1.09294808 1.92302073 1.35460361 1.07305246 1.967641  ]]]


In [9]:
#12. Multiply a and c. Assign the result to e.
e = a * c
print(a)
print(e)

[[[0.26015744 0.67305176 0.93116771 0.2224573  0.25706671]
  [0.8331111  0.62592033 0.81572585 0.23120037 0.03364045]
  [0.91207502 0.27417193 0.79667205 0.15623792 0.76216763]]

 [[0.65941125 0.83452626 0.25647604 0.93335975 0.06279051]
  [0.67468439 0.07744533 0.32012986 0.57375164 0.13633176]
  [0.09294808 0.92302073 0.35460361 0.07305246 0.967641  ]]]
[[[0.26015744 0.67305176 0.93116771 0.2224573  0.25706671]
  [0.8331111  0.62592033 0.81572585 0.23120037 0.03364045]
  [0.91207502 0.27417193 0.79667205 0.15623792 0.76216763]]

 [[0.65941125 0.83452626 0.25647604 0.93335975 0.06279051]
  [0.67468439 0.07744533 0.32012986 0.57375164 0.13633176]
  [0.09294808 0.92302073 0.35460361 0.07305246 0.967641  ]]]


In [10]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [ ]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty_like(d)



In [11]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
f = np.empty_like(d)
f[d == d_min] = 0
f[d == d_max] = 100
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50

In [12]:
#17. Print d and f. Do you have your expected f?
print(d)
print(f)

#For instance, if your d is:
#array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
 #       [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
  #      [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
#
 #      [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
  #      [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
   #     [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

#Your f should be:
#array([[[ 75.,  75.,  75.,  25.,  75.],
 #       [ 75.,  75.,  25.,  25.,  25.],
  #      [ 75.,  25.,  75.,  75.,  75.]],

   #    [[ 25.,  25.,  25.,  25., 100.],
    #    [ 75.,  75.,  75.,  75.,  75.],
     #   [ 25.,  75.,   0.,  75.,  75.]]])

[[[1.26015744 1.67305176 1.93116771 1.2224573  1.25706671]
  [1.8331111  1.62592033 1.81572585 1.23120037 1.03364045]
  [1.91207502 1.27417193 1.79667205 1.15623792 1.76216763]]

 [[1.65941125 1.83452626 1.25647604 1.93335975 1.06279051]
  [1.67468439 1.07744533 1.32012986 1.57375164 1.13633176]
  [1.09294808 1.92302073 1.35460361 1.07305246 1.967641  ]]]
[[[ 25.  75.  75.  25.  25.]
  [ 75.  75.  75.  25.   0.]
  [ 75.  25.  75.  25.  75.]]

 [[ 75.  75.  25.  75.  25.]
  [ 75.  25.  25.  75.  25.]
  [ 25.  75.  25.  25. 100.]]]


In [ ]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""